// /pages/_app.js
import Script from 'next/script'
import '../styles/globals.css'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Home/Footer'
import { useRouter } from 'next/router'

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  // চেক করছি পেজটি `[shortCode].js` কিনা
  const isRedirectPage = router.pathname === '/[shortCode]';

  return (
    <>
      <div className=''>
        <Head>
          <title>AsadTEch</title>
          <meta name="Agency Website" content="Generated by AsadTEch" />
          {/* Bootstrap CSS CDN */}
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous" />
          <link rel="stylesheet" type="text/css" charSet="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css" />
          <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css" />
        </Head>

        {/* Bootstrap JS CDN */}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossOrigin="anonymous"></Script>

        {/* নেভবার ও ফুটার দেখাবো কিনা চেক করছি */}
        {!isRedirectPage && <Navbar />}
        
        {/* মূল পেজের কন্টেন্ট */}
        <Component {...pageProps} />

        {/* ফুটার শুধুমাত্র যদি পেজটি `[shortCode]` না হয় */}
        {!isRedirectPage && <Footer />}
      </div>
    </>
  );
}

export default MyApp;
